server:
  #服务端口号
  port: 8093
spring:
  application:
    #服务名称 - 服务之间使用名称进行通讯
    name: service-demands
    #数据库信息
  datasource:
    name: test
    url: jdbc:oscar://172.19.9.254:2003/XQCHPT?serverTimezone=UTC
    username: sysdba
    password: szoscar55
    #   使用druid数据源
    driver-class-name: com.oscar.Driver
  redis:
    database: 0 # 0-15db
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1200

#MybatisPlus配置
mybatis-plus:
  mapperLocations: classpath*:static/mapper/*.xml
  typeAliasesPackage: com.cetc.plan.demand.model


eureka:
  client:
    service-url:
      #填写注册中心服务器地址
      defaultZone: http://localhost:8088/eureka
      #是否需要将自己注册到注册中心
    register-with-eureka: true
    #是否需要搜索服务信息
    fetch-registry: true
  instance:
    #使用ip地址注册到注册中心
    prefer-ip-address: true
    #注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
logging:
  level:
    root: info
    com.cetc.plan.demand.dao : debug


