server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    #服务名称 - 服务之间使用名称进行通讯
    name: service-demands
